server:
  port: 9002

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: file://${user.home}/Develop/Projects/application-config
          username : janescience
          password : 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

eureka:
  client:
    region: default
    service-url:
      defaultZone: http://localhost:9001/eureka