server:
  port: 8082

spring:
  application:
    name: department-service
  zipkin:
    base-url : http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0
  # data:
  #   mongodb:
  #     uri: mongodb+srv://janescience:Top2233223233@cluster0.xf552.mongodb.net/spring-micro-demo
  

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka