management:
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka
    fetchRegistry: true
    registerWithEureka: true
  instance:
    appname: API-GATEWAY
    preferIpAddress: true

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: CHECK-DUPLICATE-SERVICE
          uri: lb://CHECK-DUPLICATE-SERVICE
          predicates:
            - Path=/check-duplicate/**
      discovery:
        locator:
          enabled: true
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability:  1.0

server:
  port: 9000


