server:
  port: 9000

spring:
  application:
    name: gateway-proxy
  zipkin:
    baseUrl : http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0
    
zuul:
  routes:
    check-duplicate-service:
      path: /check-duplicate/**
      stripPrefix: true
  host:
    socketTimeoutMillis : 20000
    connectTimeoutMillis : 20000

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    routes:
      Enabled: true
    

eureka:
  instance:
    appname: gateway-proxy
  client:
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:9001/eureka
    healthcheck:
      enabled: true